services:
  batch-worker:
    image: ebus-backend
    build: .
    ports:
      - "${BATCH_PORT}:8000"
    environment:
      MODE: batch
    env_file:
      - .env
  stream-worker:
    image: ebus-backend
    build: .
    ports:
      - "${STREAM_PORT}:8000"
    environment:
      MODE: stream
    env_file:
      - .env
  business-service:
    image: ebus-backend
    build: .
    ports:
      - "${SERVING_PORT}:8000"
    environment:
      MODE: serving
    env_file:
      - .env
#  ui:
#    image: ebus-web
#    build: ./ui
#    ports:
#      - "3000:3000"
